{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "moderate"
		},
		"category": "csaf_security_advisory",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2023 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "Security update for python-keystoneclient",
				"title": "Title of the patch"
			},
			{
				"category": "description",
				"text": "The python-keystoneclient was updated to fix one security issues.\n\nThe following vulnerability was fixed:\n- bsc#928205: S3Token TLS cert verification option not honored (CVE-2015-1852)\n",
				"title": "Description of the patch"
			},
			{
				"category": "details",
				"text": "SUSE-SLE12-CLOUD-5-2015-303",
				"title": "Patchnames"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "self",
				"summary": "URL for SUSE-SU-2015:1208-1",
				"url": "https://www.suse.com/support/update/announcement/2015/suse-su-20151208-1/"
			},
			{
				"category": "external",
				"summary": "SUSE ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "self",
				"summary": "URL of this CSAF notice",
				"url": "https://ftp.suse.com/pub/projects/security/csaf/suse-su-2015_1208-1.json"
			},
			{
				"category": "self",
				"summary": "E-Mail link for SUSE-SU-2015:1208-1",
				"url": "https://lists.suse.com/pipermail/sle-security-updates/2015-July/001487.html"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 928205",
				"url": "https://bugzilla.suse.com/928205"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2015-1852 page",
				"url": "https://www.suse.com/security/cve/CVE-2015-1852/"
			}
		],
		"title": "Security update for python-keystoneclient",
		"tracking": {
			"current_release_date": "2015-05-13T09:07:38Z",
			"generator": {
				"date": "2015-05-13T09:07:38Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf.pl",
					"version": "1"
				}
			},
			"id": "SUSE-SU-2015:1208-1",
			"initial_release_date": "2015-05-13T09:07:38Z",
			"revision_history": [
				{
					"date": "2015-05-13T09:07:38Z",
					"number": "1",
					"summary": "Current version"
				}
			],
			"status": "final",
			"version": "1"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-keystoneclient-1.0.0-16.1.noarch",
								"product": {
									"name": "python-keystoneclient-1.0.0-16.1.noarch",
									"product_id": "python-keystoneclient-1.0.0-16.1.noarch"
								}
							},
							{
								"category": "product_version",
								"name": "python-keystoneclient-doc-1.0.0-16.1.noarch",
								"product": {
									"name": "python-keystoneclient-doc-1.0.0-16.1.noarch",
									"product_id": "python-keystoneclient-doc-1.0.0-16.1.noarch"
								}
							}
						],
						"category": "architecture",
						"name": "noarch"
					},
					{
						"branches": [
							{
								"category": "product_name",
								"name": "SUSE Cloud Compute Node for SUSE Linux Enterprise 12 5",
								"product": {
									"name": "SUSE Cloud Compute Node for SUSE Linux Enterprise 12 5",
									"product_id": "SUSE Cloud Compute Node for SUSE Linux Enterprise 12 5",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:suse-sle12-cloud-compute:5"
									}
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-keystoneclient-1.0.0-16.1.noarch as component of SUSE Cloud Compute Node for SUSE Linux Enterprise 12 5",
					"product_id": "SUSE Cloud Compute Node for SUSE Linux Enterprise 12 5:python-keystoneclient-1.0.0-16.1.noarch"
				},
				"product_reference": "python-keystoneclient-1.0.0-16.1.noarch",
				"relates_to_product_reference": "SUSE Cloud Compute Node for SUSE Linux Enterprise 12 5"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-keystoneclient-doc-1.0.0-16.1.noarch as component of SUSE Cloud Compute Node for SUSE Linux Enterprise 12 5",
					"product_id": "SUSE Cloud Compute Node for SUSE Linux Enterprise 12 5:python-keystoneclient-doc-1.0.0-16.1.noarch"
				},
				"product_reference": "python-keystoneclient-doc-1.0.0-16.1.noarch",
				"relates_to_product_reference": "SUSE Cloud Compute Node for SUSE Linux Enterprise 12 5"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2015-1852",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2015-1852"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "The s3_token middleware in OpenStack keystonemiddleware before 1.6.0 and python-keystoneclient before 1.4.0 disables certification verification when the \"insecure\" option is set in a paste configuration (paste.ini) file regardless of the value, which allows remote attackers to conduct man-in-the-middle attacks via a crafted certificate, a different vulnerability than CVE-2014-7144.",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE Cloud Compute Node for SUSE Linux Enterprise 12 5:python-keystoneclient-1.0.0-16.1.noarch",
					"SUSE Cloud Compute Node for SUSE Linux Enterprise 12 5:python-keystoneclient-doc-1.0.0-16.1.noarch"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2015-1852",
					"url": "https://www.suse.com/security/cve/CVE-2015-1852"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 928205 for CVE-2015-1852",
					"url": "https://bugzilla.suse.com/928205"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE Cloud Compute Node for SUSE Linux Enterprise 12 5:python-keystoneclient-1.0.0-16.1.noarch",
						"SUSE Cloud Compute Node for SUSE Linux Enterprise 12 5:python-keystoneclient-doc-1.0.0-16.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2015-05-13T09:07:38Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2015-1852"
		}
	]
}
