{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "moderate"
		},
		"category": "csaf_security_advisory",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2023 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "Security update for python-ecdsa",
				"title": "Title of the patch"
			},
			{
				"category": "description",
				"text": "This update for python-ecdsa to version 0.13.3 fixes the following issues:\n\nSecurity issues fixed:\n\n- CVE-2019-14853: Fixed unexpected exceptions during signature decoding (bsc#1153165).\n- CVE-2019-14859: Fixed a signature malleability caused by insufficient checks of DER encoding (bsc#1154217).\n\nThis update was imported from the SUSE:SLE-15:Update update project.",
				"title": "Description of the patch"
			},
			{
				"category": "details",
				"text": "openSUSE-2019-2472",
				"title": "Patchnames"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "self",
				"summary": "URL for openSUSE-SU-2019:2472-1",
				"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/AE4KLR5KRHYPXZBHUHGSASFQO5DPZRAN/#AE4KLR5KRHYPXZBHUHGSASFQO5DPZRAN"
			},
			{
				"category": "external",
				"summary": "SUSE ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "self",
				"summary": "URL of this CSAF notice",
				"url": "https://ftp.suse.com/pub/projects/security/csaf/opensuse-su-2019_2472-1.json"
			},
			{
				"category": "self",
				"summary": "E-Mail link for openSUSE-SU-2019:2472-1",
				"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/AE4KLR5KRHYPXZBHUHGSASFQO5DPZRAN/#AE4KLR5KRHYPXZBHUHGSASFQO5DPZRAN"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1153165",
				"url": "https://bugzilla.suse.com/1153165"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1154217",
				"url": "https://bugzilla.suse.com/1154217"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2019-14853 page",
				"url": "https://www.suse.com/security/cve/CVE-2019-14853/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2019-14859 page",
				"url": "https://www.suse.com/security/cve/CVE-2019-14859/"
			}
		],
		"title": "Security update for python-ecdsa",
		"tracking": {
			"current_release_date": "2019-11-09T23:20:27Z",
			"generator": {
				"date": "2019-11-09T23:20:27Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf.pl",
					"version": "1"
				}
			},
			"id": "openSUSE-SU-2019:2472-1",
			"initial_release_date": "2019-11-09T23:20:27Z",
			"revision_history": [
				{
					"date": "2019-11-09T23:20:27Z",
					"number": "1",
					"summary": "Current version"
				}
			],
			"status": "final",
			"version": "1"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python2-ecdsa-0.13.3-lp150.2.3.1.noarch",
								"product": {
									"name": "python2-ecdsa-0.13.3-lp150.2.3.1.noarch",
									"product_id": "python2-ecdsa-0.13.3-lp150.2.3.1.noarch"
								}
							},
							{
								"category": "product_version",
								"name": "python3-ecdsa-0.13.3-lp150.2.3.1.noarch",
								"product": {
									"name": "python3-ecdsa-0.13.3-lp150.2.3.1.noarch",
									"product_id": "python3-ecdsa-0.13.3-lp150.2.3.1.noarch"
								}
							}
						],
						"category": "architecture",
						"name": "noarch"
					},
					{
						"branches": [
							{
								"category": "product_name",
								"name": "openSUSE Leap 15.0",
								"product": {
									"name": "openSUSE Leap 15.0",
									"product_id": "openSUSE Leap 15.0",
									"product_identification_helper": {
										"cpe": "cpe:/o:opensuse:leap:15.0"
									}
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python2-ecdsa-0.13.3-lp150.2.3.1.noarch as component of openSUSE Leap 15.0",
					"product_id": "openSUSE Leap 15.0:python2-ecdsa-0.13.3-lp150.2.3.1.noarch"
				},
				"product_reference": "python2-ecdsa-0.13.3-lp150.2.3.1.noarch",
				"relates_to_product_reference": "openSUSE Leap 15.0"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python3-ecdsa-0.13.3-lp150.2.3.1.noarch as component of openSUSE Leap 15.0",
					"product_id": "openSUSE Leap 15.0:python3-ecdsa-0.13.3-lp150.2.3.1.noarch"
				},
				"product_reference": "python3-ecdsa-0.13.3-lp150.2.3.1.noarch",
				"relates_to_product_reference": "openSUSE Leap 15.0"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2019-14853",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2019-14853"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "An error-handling flaw was found in python-ecdsa before version 0.13.3. During signature decoding, malformed DER signatures could raise unexpected exceptions (or no exceptions at all), which could lead to a denial of service.",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"openSUSE Leap 15.0:python2-ecdsa-0.13.3-lp150.2.3.1.noarch",
					"openSUSE Leap 15.0:python3-ecdsa-0.13.3-lp150.2.3.1.noarch"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2019-14853",
					"url": "https://www.suse.com/security/cve/CVE-2019-14853"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1153165 for CVE-2019-14853",
					"url": "https://bugzilla.suse.com/1153165"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Leap 15.0:python2-ecdsa-0.13.3-lp150.2.3.1.noarch",
						"openSUSE Leap 15.0:python3-ecdsa-0.13.3-lp150.2.3.1.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 5.3,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
						"version": "3.0"
					},
					"products": [
						"openSUSE Leap 15.0:python2-ecdsa-0.13.3-lp150.2.3.1.noarch",
						"openSUSE Leap 15.0:python3-ecdsa-0.13.3-lp150.2.3.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2019-11-09T23:20:27Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2019-14853"
		},
		{
			"cve": "CVE-2019-14859",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2019-14859"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "A flaw was found in all python-ecdsa versions before 0.13.3, where it did not correctly verify whether signatures used DER encoding. Without this verification, a malformed signature could be accepted, making the signature malleable. Without proper verification, an attacker could use a malleable signature to create false transactions.",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"openSUSE Leap 15.0:python2-ecdsa-0.13.3-lp150.2.3.1.noarch",
					"openSUSE Leap 15.0:python3-ecdsa-0.13.3-lp150.2.3.1.noarch"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2019-14859",
					"url": "https://www.suse.com/security/cve/CVE-2019-14859"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1154217 for CVE-2019-14859",
					"url": "https://bugzilla.suse.com/1154217"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Leap 15.0:python2-ecdsa-0.13.3-lp150.2.3.1.noarch",
						"openSUSE Leap 15.0:python3-ecdsa-0.13.3-lp150.2.3.1.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 6.8,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.0/AV:L/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:L",
						"version": "3.0"
					},
					"products": [
						"openSUSE Leap 15.0:python2-ecdsa-0.13.3-lp150.2.3.1.noarch",
						"openSUSE Leap 15.0:python3-ecdsa-0.13.3-lp150.2.3.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2019-11-09T23:20:27Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2019-14859"
		}
	]
}
