{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "important"
		},
		"category": "csaf_security_advisory",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2024 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "Security update for python-SQLAlchemy",
				"title": "Title of the patch"
			},
			{
				"category": "description",
				"text": "This update for python-SQLAlchemy fixes the following issues:\n\nSecurity issues fixed:\n\n- CVE-2019-7164: Fixed SQL Injection via the order_by parameter (bsc#1124593).\n- CVE-2019-7548: Fixed SQL Injection via the group_by parameter (bsc#1124593).\n",
				"title": "Description of the patch"
			},
			{
				"category": "details",
				"text": "SUSE-2019-2350,SUSE-OpenStack-Cloud-7-2019-2350,SUSE-Storage-4-2019-2350",
				"title": "Patchnames"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "external",
				"summary": "SUSE ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "self",
				"summary": "URL of this CSAF notice",
				"url": "https://ftp.suse.com/pub/projects/security/csaf/suse-su-2019_2350-1.json"
			},
			{
				"category": "self",
				"summary": "URL for SUSE-SU-2019:2350-1",
				"url": "https://www.suse.com/support/update/announcement/2019/suse-su-20192350-1/"
			},
			{
				"category": "self",
				"summary": "E-Mail link for SUSE-SU-2019:2350-1",
				"url": "https://lists.suse.com/pipermail/sle-security-updates/2019-September/005905.html"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1124593",
				"url": "https://bugzilla.suse.com/1124593"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2019-7164 page",
				"url": "https://www.suse.com/security/cve/CVE-2019-7164/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2019-7548 page",
				"url": "https://www.suse.com/security/cve/CVE-2019-7548/"
			}
		],
		"title": "Security update for python-SQLAlchemy",
		"tracking": {
			"current_release_date": "2019-09-10T13:39:50Z",
			"generator": {
				"date": "2019-09-10T13:39:50Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf.pl",
					"version": "1"
				}
			},
			"id": "SUSE-SU-2019:2350-1",
			"initial_release_date": "2019-09-10T13:39:50Z",
			"revision_history": [
				{
					"date": "2019-09-10T13:39:50Z",
					"number": "1",
					"summary": "Current version"
				}
			],
			"status": "final",
			"version": "1"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-SQLAlchemy-1.0.14-4.3.1.aarch64",
								"product": {
									"name": "python-SQLAlchemy-1.0.14-4.3.1.aarch64",
									"product_id": "python-SQLAlchemy-1.0.14-4.3.1.aarch64"
								}
							}
						],
						"category": "architecture",
						"name": "aarch64"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-SQLAlchemy-doc-1.0.14-4.3.1.noarch",
								"product": {
									"name": "python-SQLAlchemy-doc-1.0.14-4.3.1.noarch",
									"product_id": "python-SQLAlchemy-doc-1.0.14-4.3.1.noarch"
								}
							}
						],
						"category": "architecture",
						"name": "noarch"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-SQLAlchemy-1.0.14-4.3.1.ppc64le",
								"product": {
									"name": "python-SQLAlchemy-1.0.14-4.3.1.ppc64le",
									"product_id": "python-SQLAlchemy-1.0.14-4.3.1.ppc64le"
								}
							}
						],
						"category": "architecture",
						"name": "ppc64le"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-SQLAlchemy-1.0.14-4.3.1.s390x",
								"product": {
									"name": "python-SQLAlchemy-1.0.14-4.3.1.s390x",
									"product_id": "python-SQLAlchemy-1.0.14-4.3.1.s390x"
								}
							}
						],
						"category": "architecture",
						"name": "s390x"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-SQLAlchemy-1.0.14-4.3.1.x86_64",
								"product": {
									"name": "python-SQLAlchemy-1.0.14-4.3.1.x86_64",
									"product_id": "python-SQLAlchemy-1.0.14-4.3.1.x86_64"
								}
							}
						],
						"category": "architecture",
						"name": "x86_64"
					},
					{
						"branches": [
							{
								"category": "product_name",
								"name": "SUSE OpenStack Cloud 7",
								"product": {
									"name": "SUSE OpenStack Cloud 7",
									"product_id": "SUSE OpenStack Cloud 7",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:suse-openstack-cloud:7"
									}
								}
							},
							{
								"category": "product_name",
								"name": "SUSE Enterprise Storage 4",
								"product": {
									"name": "SUSE Enterprise Storage 4",
									"product_id": "SUSE Enterprise Storage 4",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:ses:4"
									}
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-SQLAlchemy-1.0.14-4.3.1.aarch64 as component of SUSE OpenStack Cloud 7",
					"product_id": "SUSE OpenStack Cloud 7:python-SQLAlchemy-1.0.14-4.3.1.aarch64"
				},
				"product_reference": "python-SQLAlchemy-1.0.14-4.3.1.aarch64",
				"relates_to_product_reference": "SUSE OpenStack Cloud 7"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-SQLAlchemy-1.0.14-4.3.1.s390x as component of SUSE OpenStack Cloud 7",
					"product_id": "SUSE OpenStack Cloud 7:python-SQLAlchemy-1.0.14-4.3.1.s390x"
				},
				"product_reference": "python-SQLAlchemy-1.0.14-4.3.1.s390x",
				"relates_to_product_reference": "SUSE OpenStack Cloud 7"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-SQLAlchemy-1.0.14-4.3.1.x86_64 as component of SUSE OpenStack Cloud 7",
					"product_id": "SUSE OpenStack Cloud 7:python-SQLAlchemy-1.0.14-4.3.1.x86_64"
				},
				"product_reference": "python-SQLAlchemy-1.0.14-4.3.1.x86_64",
				"relates_to_product_reference": "SUSE OpenStack Cloud 7"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-SQLAlchemy-1.0.14-4.3.1.aarch64 as component of SUSE Enterprise Storage 4",
					"product_id": "SUSE Enterprise Storage 4:python-SQLAlchemy-1.0.14-4.3.1.aarch64"
				},
				"product_reference": "python-SQLAlchemy-1.0.14-4.3.1.aarch64",
				"relates_to_product_reference": "SUSE Enterprise Storage 4"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-SQLAlchemy-1.0.14-4.3.1.x86_64 as component of SUSE Enterprise Storage 4",
					"product_id": "SUSE Enterprise Storage 4:python-SQLAlchemy-1.0.14-4.3.1.x86_64"
				},
				"product_reference": "python-SQLAlchemy-1.0.14-4.3.1.x86_64",
				"relates_to_product_reference": "SUSE Enterprise Storage 4"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2019-7164",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2019-7164"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "SQLAlchemy through 1.2.17 and 1.3.x through 1.3.0b2 allows SQL Injection via the order_by parameter.",
					"title": "CVE description"
				}
			],
			"product_status": {},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2019-7164",
					"url": "https://www.suse.com/security/cve/CVE-2019-7164"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1124593 for CVE-2019-7164",
					"url": "https://bugzilla.suse.com/1124593"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE Enterprise Storage 4:python-SQLAlchemy-1.0.14-4.3.1.aarch64",
						"SUSE Enterprise Storage 4:python-SQLAlchemy-1.0.14-4.3.1.x86_64",
						"SUSE OpenStack Cloud 7:python-SQLAlchemy-1.0.14-4.3.1.aarch64",
						"SUSE OpenStack Cloud 7:python-SQLAlchemy-1.0.14-4.3.1.s390x",
						"SUSE OpenStack Cloud 7:python-SQLAlchemy-1.0.14-4.3.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 8.8,
						"baseSeverity": "HIGH",
						"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
						"version": "3.0"
					},
					"products": [
						"SUSE Enterprise Storage 4:python-SQLAlchemy-1.0.14-4.3.1.aarch64",
						"SUSE Enterprise Storage 4:python-SQLAlchemy-1.0.14-4.3.1.x86_64",
						"SUSE OpenStack Cloud 7:python-SQLAlchemy-1.0.14-4.3.1.aarch64",
						"SUSE OpenStack Cloud 7:python-SQLAlchemy-1.0.14-4.3.1.s390x",
						"SUSE OpenStack Cloud 7:python-SQLAlchemy-1.0.14-4.3.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2019-09-10T13:39:50Z",
					"details": "important"
				}
			],
			"title": "CVE-2019-7164"
		},
		{
			"cve": "CVE-2019-7548",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2019-7548"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "SQLAlchemy 1.2.17 has SQL Injection when the group_by parameter can be controlled.",
					"title": "CVE description"
				}
			],
			"product_status": {},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2019-7548",
					"url": "https://www.suse.com/security/cve/CVE-2019-7548"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1124593 for CVE-2019-7548",
					"url": "https://bugzilla.suse.com/1124593"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE Enterprise Storage 4:python-SQLAlchemy-1.0.14-4.3.1.aarch64",
						"SUSE Enterprise Storage 4:python-SQLAlchemy-1.0.14-4.3.1.x86_64",
						"SUSE OpenStack Cloud 7:python-SQLAlchemy-1.0.14-4.3.1.aarch64",
						"SUSE OpenStack Cloud 7:python-SQLAlchemy-1.0.14-4.3.1.s390x",
						"SUSE OpenStack Cloud 7:python-SQLAlchemy-1.0.14-4.3.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 8.8,
						"baseSeverity": "HIGH",
						"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
						"version": "3.0"
					},
					"products": [
						"SUSE Enterprise Storage 4:python-SQLAlchemy-1.0.14-4.3.1.aarch64",
						"SUSE Enterprise Storage 4:python-SQLAlchemy-1.0.14-4.3.1.x86_64",
						"SUSE OpenStack Cloud 7:python-SQLAlchemy-1.0.14-4.3.1.aarch64",
						"SUSE OpenStack Cloud 7:python-SQLAlchemy-1.0.14-4.3.1.s390x",
						"SUSE OpenStack Cloud 7:python-SQLAlchemy-1.0.14-4.3.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2019-09-10T13:39:50Z",
					"details": "important"
				}
			],
			"title": "CVE-2019-7548"
		}
	]
}
