{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "moderate"
		},
		"category": "csaf_security_advisory",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2024 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "Security update for python-Django",
				"title": "Title of the patch"
			},
			{
				"category": "description",
				"text": "This update for python-Django fixes the following issues:\n\n- CVE-2023-43665: Fixed a Denial-of-service in django.utils.text.Truncator. (bsc#1215978)\n",
				"title": "Description of the patch"
			},
			{
				"category": "details",
				"text": "HPE-Helion-OpenStack-8-2023-4232,SUSE-2023-4232,SUSE-OpenStack-Cloud-8-2023-4232,SUSE-OpenStack-Cloud-Crowbar-8-2023-4232",
				"title": "Patchnames"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "external",
				"summary": "SUSE ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "self",
				"summary": "URL of this CSAF notice",
				"url": "https://ftp.suse.com/pub/projects/security/csaf/suse-su-2023_4232-1.json"
			},
			{
				"category": "self",
				"summary": "URL for SUSE-SU-2023:4232-1",
				"url": "https://www.suse.com/support/update/announcement/2023/suse-su-20234232-1/"
			},
			{
				"category": "self",
				"summary": "E-Mail link for SUSE-SU-2023:4232-1",
				"url": "https://lists.suse.com/pipermail/sle-security-updates/2023-October/016894.html"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1215978",
				"url": "https://bugzilla.suse.com/1215978"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2023-43665 page",
				"url": "https://www.suse.com/security/cve/CVE-2023-43665/"
			}
		],
		"title": "Security update for python-Django",
		"tracking": {
			"current_release_date": "2023-10-27T14:43:23Z",
			"generator": {
				"date": "2023-10-27T14:43:23Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf.pl",
					"version": "1"
				}
			},
			"id": "SUSE-SU-2023:4232-1",
			"initial_release_date": "2023-10-27T14:43:23Z",
			"revision_history": [
				{
					"date": "2023-10-27T14:43:23Z",
					"number": "1",
					"summary": "Current version"
				}
			],
			"status": "final",
			"version": "1"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-Django-1.11.29-3.54.1.noarch",
								"product": {
									"name": "python-Django-1.11.29-3.54.1.noarch",
									"product_id": "python-Django-1.11.29-3.54.1.noarch"
								}
							},
							{
								"category": "product_version",
								"name": "python3-Django-1.11.29-3.54.1.noarch",
								"product": {
									"name": "python3-Django-1.11.29-3.54.1.noarch",
									"product_id": "python3-Django-1.11.29-3.54.1.noarch"
								}
							}
						],
						"category": "architecture",
						"name": "noarch"
					},
					{
						"branches": [
							{
								"category": "product_name",
								"name": "HPE Helion OpenStack 8",
								"product": {
									"name": "HPE Helion OpenStack 8",
									"product_id": "HPE Helion OpenStack 8",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:hpe-helion-openstack:8"
									}
								}
							},
							{
								"category": "product_name",
								"name": "SUSE OpenStack Cloud 8",
								"product": {
									"name": "SUSE OpenStack Cloud 8",
									"product_id": "SUSE OpenStack Cloud 8",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:suse-openstack-cloud:8"
									}
								}
							},
							{
								"category": "product_name",
								"name": "SUSE OpenStack Cloud Crowbar 8",
								"product": {
									"name": "SUSE OpenStack Cloud Crowbar 8",
									"product_id": "SUSE OpenStack Cloud Crowbar 8",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:suse-openstack-cloud-crowbar:8"
									}
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-Django-1.11.29-3.54.1.noarch as component of HPE Helion OpenStack 8",
					"product_id": "HPE Helion OpenStack 8:python-Django-1.11.29-3.54.1.noarch"
				},
				"product_reference": "python-Django-1.11.29-3.54.1.noarch",
				"relates_to_product_reference": "HPE Helion OpenStack 8"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-Django-1.11.29-3.54.1.noarch as component of SUSE OpenStack Cloud 8",
					"product_id": "SUSE OpenStack Cloud 8:python-Django-1.11.29-3.54.1.noarch"
				},
				"product_reference": "python-Django-1.11.29-3.54.1.noarch",
				"relates_to_product_reference": "SUSE OpenStack Cloud 8"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-Django-1.11.29-3.54.1.noarch as component of SUSE OpenStack Cloud Crowbar 8",
					"product_id": "SUSE OpenStack Cloud Crowbar 8:python-Django-1.11.29-3.54.1.noarch"
				},
				"product_reference": "python-Django-1.11.29-3.54.1.noarch",
				"relates_to_product_reference": "SUSE OpenStack Cloud Crowbar 8"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2023-43665",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2023-43665"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "In Django 3.2 before 3.2.22, 4.1 before 4.1.12, and 4.2 before 4.2.6, the django.utils.text.Truncator chars() and words() methods (when used with html=True) are subject to a potential DoS (denial of service) attack via certain inputs with very long, potentially malformed HTML text. The chars() and words() methods are used to implement the truncatechars_html and truncatewords_html template filters, which are thus also vulnerable. NOTE: this issue exists because of an incomplete fix for CVE-2019-14232.",
					"title": "CVE description"
				}
			],
			"product_status": {},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2023-43665",
					"url": "https://www.suse.com/security/cve/CVE-2023-43665"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1215978 for CVE-2023-43665",
					"url": "https://bugzilla.suse.com/1215978"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1220358 for CVE-2023-43665",
					"url": "https://bugzilla.suse.com/1220358"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"HPE Helion OpenStack 8:python-Django-1.11.29-3.54.1.noarch",
						"SUSE OpenStack Cloud 8:python-Django-1.11.29-3.54.1.noarch",
						"SUSE OpenStack Cloud Crowbar 8:python-Django-1.11.29-3.54.1.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 5.3,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
						"version": "3.1"
					},
					"products": [
						"HPE Helion OpenStack 8:python-Django-1.11.29-3.54.1.noarch",
						"SUSE OpenStack Cloud 8:python-Django-1.11.29-3.54.1.noarch",
						"SUSE OpenStack Cloud Crowbar 8:python-Django-1.11.29-3.54.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2023-10-27T14:43:23Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2023-43665"
		}
	]
}
