{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "moderate"
		},
		"category": "csaf_security_advisory",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2024 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "python310-grpcio-1.60.0-2.1 on GA media",
				"title": "Title of the patch"
			},
			{
				"category": "description",
				"text": "These are all security issues fixed in the python310-grpcio-1.60.0-2.1 package on the GA media of openSUSE Tumbleweed.",
				"title": "Description of the patch"
			},
			{
				"category": "details",
				"text": "openSUSE-Tumbleweed-2024-13634",
				"title": "Patchnames"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "external",
				"summary": "SUSE ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "self",
				"summary": "URL of this CSAF notice",
				"url": "https://ftp.suse.com/pub/projects/security/csaf/opensuse-su-2024_13634-1.json"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2023-32731 page",
				"url": "https://www.suse.com/security/cve/CVE-2023-32731/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2023-32732 page",
				"url": "https://www.suse.com/security/cve/CVE-2023-32732/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2023-4785 page",
				"url": "https://www.suse.com/security/cve/CVE-2023-4785/"
			}
		],
		"title": "python310-grpcio-1.60.0-2.1 on GA media",
		"tracking": {
			"current_release_date": "2024-06-15T00:00:00Z",
			"generator": {
				"date": "2024-06-15T00:00:00Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf.pl",
					"version": "1"
				}
			},
			"id": "openSUSE-SU-2024:13634-1",
			"initial_release_date": "2024-06-15T00:00:00Z",
			"revision_history": [
				{
					"date": "2024-06-15T00:00:00Z",
					"number": "1",
					"summary": "Current version"
				}
			],
			"status": "final",
			"version": "1"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python310-grpcio-1.60.0-2.1.aarch64",
								"product": {
									"name": "python310-grpcio-1.60.0-2.1.aarch64",
									"product_id": "python310-grpcio-1.60.0-2.1.aarch64"
								}
							},
							{
								"category": "product_version",
								"name": "python311-grpcio-1.60.0-2.1.aarch64",
								"product": {
									"name": "python311-grpcio-1.60.0-2.1.aarch64",
									"product_id": "python311-grpcio-1.60.0-2.1.aarch64"
								}
							},
							{
								"category": "product_version",
								"name": "python39-grpcio-1.60.0-2.1.aarch64",
								"product": {
									"name": "python39-grpcio-1.60.0-2.1.aarch64",
									"product_id": "python39-grpcio-1.60.0-2.1.aarch64"
								}
							}
						],
						"category": "architecture",
						"name": "aarch64"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python310-grpcio-1.60.0-2.1.ppc64le",
								"product": {
									"name": "python310-grpcio-1.60.0-2.1.ppc64le",
									"product_id": "python310-grpcio-1.60.0-2.1.ppc64le"
								}
							},
							{
								"category": "product_version",
								"name": "python311-grpcio-1.60.0-2.1.ppc64le",
								"product": {
									"name": "python311-grpcio-1.60.0-2.1.ppc64le",
									"product_id": "python311-grpcio-1.60.0-2.1.ppc64le"
								}
							},
							{
								"category": "product_version",
								"name": "python39-grpcio-1.60.0-2.1.ppc64le",
								"product": {
									"name": "python39-grpcio-1.60.0-2.1.ppc64le",
									"product_id": "python39-grpcio-1.60.0-2.1.ppc64le"
								}
							}
						],
						"category": "architecture",
						"name": "ppc64le"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python310-grpcio-1.60.0-2.1.s390x",
								"product": {
									"name": "python310-grpcio-1.60.0-2.1.s390x",
									"product_id": "python310-grpcio-1.60.0-2.1.s390x"
								}
							},
							{
								"category": "product_version",
								"name": "python311-grpcio-1.60.0-2.1.s390x",
								"product": {
									"name": "python311-grpcio-1.60.0-2.1.s390x",
									"product_id": "python311-grpcio-1.60.0-2.1.s390x"
								}
							},
							{
								"category": "product_version",
								"name": "python39-grpcio-1.60.0-2.1.s390x",
								"product": {
									"name": "python39-grpcio-1.60.0-2.1.s390x",
									"product_id": "python39-grpcio-1.60.0-2.1.s390x"
								}
							}
						],
						"category": "architecture",
						"name": "s390x"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python310-grpcio-1.60.0-2.1.x86_64",
								"product": {
									"name": "python310-grpcio-1.60.0-2.1.x86_64",
									"product_id": "python310-grpcio-1.60.0-2.1.x86_64"
								}
							},
							{
								"category": "product_version",
								"name": "python311-grpcio-1.60.0-2.1.x86_64",
								"product": {
									"name": "python311-grpcio-1.60.0-2.1.x86_64",
									"product_id": "python311-grpcio-1.60.0-2.1.x86_64"
								}
							},
							{
								"category": "product_version",
								"name": "python39-grpcio-1.60.0-2.1.x86_64",
								"product": {
									"name": "python39-grpcio-1.60.0-2.1.x86_64",
									"product_id": "python39-grpcio-1.60.0-2.1.x86_64"
								}
							}
						],
						"category": "architecture",
						"name": "x86_64"
					},
					{
						"branches": [
							{
								"category": "product_name",
								"name": "openSUSE Tumbleweed",
								"product": {
									"name": "openSUSE Tumbleweed",
									"product_id": "openSUSE Tumbleweed",
									"product_identification_helper": {
										"cpe": "cpe:/o:opensuse:tumbleweed"
									}
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python310-grpcio-1.60.0-2.1.aarch64 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.aarch64"
				},
				"product_reference": "python310-grpcio-1.60.0-2.1.aarch64",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python310-grpcio-1.60.0-2.1.ppc64le as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.ppc64le"
				},
				"product_reference": "python310-grpcio-1.60.0-2.1.ppc64le",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python310-grpcio-1.60.0-2.1.s390x as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.s390x"
				},
				"product_reference": "python310-grpcio-1.60.0-2.1.s390x",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python310-grpcio-1.60.0-2.1.x86_64 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.x86_64"
				},
				"product_reference": "python310-grpcio-1.60.0-2.1.x86_64",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python311-grpcio-1.60.0-2.1.aarch64 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.aarch64"
				},
				"product_reference": "python311-grpcio-1.60.0-2.1.aarch64",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python311-grpcio-1.60.0-2.1.ppc64le as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.ppc64le"
				},
				"product_reference": "python311-grpcio-1.60.0-2.1.ppc64le",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python311-grpcio-1.60.0-2.1.s390x as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.s390x"
				},
				"product_reference": "python311-grpcio-1.60.0-2.1.s390x",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python311-grpcio-1.60.0-2.1.x86_64 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.x86_64"
				},
				"product_reference": "python311-grpcio-1.60.0-2.1.x86_64",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python39-grpcio-1.60.0-2.1.aarch64 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.aarch64"
				},
				"product_reference": "python39-grpcio-1.60.0-2.1.aarch64",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python39-grpcio-1.60.0-2.1.ppc64le as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.ppc64le"
				},
				"product_reference": "python39-grpcio-1.60.0-2.1.ppc64le",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python39-grpcio-1.60.0-2.1.s390x as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.s390x"
				},
				"product_reference": "python39-grpcio-1.60.0-2.1.s390x",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python39-grpcio-1.60.0-2.1.x86_64 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.x86_64"
				},
				"product_reference": "python39-grpcio-1.60.0-2.1.x86_64",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2023-32731",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2023-32731"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "When gRPC HTTP2 stack raised a header size exceeded error, it skipped parsing the rest of the HPACK frame. This caused any HPACK table mutations to also be skipped, resulting in a desynchronization of HPACK tables between sender and receiver. If leveraged, say, between a proxy and a backend, this could lead to requests from the proxy being interpreted as containing headers from different proxy clients - leading to an information leak that can be used for privilege escalation or data exfiltration. We recommend upgrading beyond the commit contained in  https://github.com/grpc/grpc/pull/33005 https://github.com/grpc/grpc/pull/33005 \n",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.aarch64",
					"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.ppc64le",
					"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.s390x",
					"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.x86_64",
					"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.aarch64",
					"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.ppc64le",
					"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.s390x",
					"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.x86_64",
					"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.aarch64",
					"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.s390x",
					"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2023-32731",
					"url": "https://www.suse.com/security/cve/CVE-2023-32731"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1212180 for CVE-2023-32731",
					"url": "https://bugzilla.suse.com/1212180"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.aarch64",
						"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.ppc64le",
						"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.s390x",
						"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.x86_64",
						"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.aarch64",
						"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.ppc64le",
						"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.s390x",
						"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.x86_64",
						"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.aarch64",
						"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.s390x",
						"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 7.4,
						"baseSeverity": "HIGH",
						"vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:H",
						"version": "3.1"
					},
					"products": [
						"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.aarch64",
						"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.ppc64le",
						"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.s390x",
						"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.x86_64",
						"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.aarch64",
						"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.ppc64le",
						"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.s390x",
						"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.x86_64",
						"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.aarch64",
						"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.s390x",
						"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-06-15T00:00:00Z",
					"details": "important"
				}
			],
			"title": "CVE-2023-32731"
		},
		{
			"cve": "CVE-2023-32732",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2023-32732"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "gRPC contains a vulnerability whereby a client can cause a termination of connection between a HTTP2 proxy and a gRPC server: a base64 encoding error for `-bin` suffixed headers will result in a disconnection by the gRPC server, but is typically allowed by HTTP2 proxies. We recommend upgrading beyond the commit in  https://github.com/grpc/grpc/pull/32309 https://www.google.com/url \n",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.aarch64",
					"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.ppc64le",
					"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.s390x",
					"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.x86_64",
					"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.aarch64",
					"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.ppc64le",
					"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.s390x",
					"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.x86_64",
					"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.aarch64",
					"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.s390x",
					"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2023-32732",
					"url": "https://www.suse.com/security/cve/CVE-2023-32732"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1212182 for CVE-2023-32732",
					"url": "https://bugzilla.suse.com/1212182"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.aarch64",
						"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.ppc64le",
						"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.s390x",
						"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.x86_64",
						"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.aarch64",
						"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.ppc64le",
						"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.s390x",
						"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.x86_64",
						"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.aarch64",
						"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.s390x",
						"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 5.3,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
						"version": "3.1"
					},
					"products": [
						"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.aarch64",
						"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.ppc64le",
						"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.s390x",
						"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.x86_64",
						"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.aarch64",
						"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.ppc64le",
						"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.s390x",
						"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.x86_64",
						"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.aarch64",
						"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.s390x",
						"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-06-15T00:00:00Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2023-32732"
		},
		{
			"cve": "CVE-2023-4785",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2023-4785"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "Lack of error handling in the TCP server in Google's gRPC starting version 1.23 on posix-compatible platforms (ex. Linux) allows an attacker to cause a denial of service by initiating a significant number of connections with the server. Note that gRPC C++ Python, and Ruby are affected, but gRPC Java, and Go are NOT affected. ",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.aarch64",
					"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.ppc64le",
					"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.s390x",
					"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.x86_64",
					"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.aarch64",
					"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.ppc64le",
					"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.s390x",
					"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.x86_64",
					"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.aarch64",
					"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.s390x",
					"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2023-4785",
					"url": "https://www.suse.com/security/cve/CVE-2023-4785"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1215334 for CVE-2023-4785",
					"url": "https://bugzilla.suse.com/1215334"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.aarch64",
						"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.ppc64le",
						"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.s390x",
						"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.x86_64",
						"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.aarch64",
						"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.ppc64le",
						"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.s390x",
						"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.x86_64",
						"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.aarch64",
						"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.s390x",
						"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 7.5,
						"baseSeverity": "HIGH",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
						"version": "3.1"
					},
					"products": [
						"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.aarch64",
						"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.ppc64le",
						"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.s390x",
						"openSUSE Tumbleweed:python310-grpcio-1.60.0-2.1.x86_64",
						"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.aarch64",
						"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.ppc64le",
						"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.s390x",
						"openSUSE Tumbleweed:python311-grpcio-1.60.0-2.1.x86_64",
						"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.aarch64",
						"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.s390x",
						"openSUSE Tumbleweed:python39-grpcio-1.60.0-2.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-06-15T00:00:00Z",
					"details": "important"
				}
			],
			"title": "CVE-2023-4785"
		}
	]
}
