{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "moderate"
		},
		"category": "csaf_security_advisory",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2024 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "python310-kubernetes-28.1.0-4.3 on GA media",
				"title": "Title of the patch"
			},
			{
				"category": "description",
				"text": "These are all security issues fixed in the python310-kubernetes-28.1.0-4.3 package on the GA media of openSUSE Tumbleweed.",
				"title": "Description of the patch"
			},
			{
				"category": "details",
				"text": "openSUSE-Tumbleweed-2024-14144",
				"title": "Patchnames"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "external",
				"summary": "SUSE ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "self",
				"summary": "URL of this CSAF notice",
				"url": "https://ftp.suse.com/pub/projects/security/csaf/opensuse-su-2024_14144-1.json"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2018-20060 page",
				"url": "https://www.suse.com/security/cve/CVE-2018-20060/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2019-11324 page",
				"url": "https://www.suse.com/security/cve/CVE-2019-11324/"
			}
		],
		"title": "python310-kubernetes-28.1.0-4.3 on GA media",
		"tracking": {
			"current_release_date": "2024-07-12T00:00:00Z",
			"generator": {
				"date": "2024-07-12T00:00:00Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf.pl",
					"version": "1"
				}
			},
			"id": "openSUSE-SU-2024:14144-1",
			"initial_release_date": "2024-07-12T00:00:00Z",
			"revision_history": [
				{
					"date": "2024-07-12T00:00:00Z",
					"number": "1",
					"summary": "Current version"
				}
			],
			"status": "final",
			"version": "1"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python310-kubernetes-28.1.0-4.3.aarch64",
								"product": {
									"name": "python310-kubernetes-28.1.0-4.3.aarch64",
									"product_id": "python310-kubernetes-28.1.0-4.3.aarch64"
								}
							},
							{
								"category": "product_version",
								"name": "python311-kubernetes-28.1.0-4.3.aarch64",
								"product": {
									"name": "python311-kubernetes-28.1.0-4.3.aarch64",
									"product_id": "python311-kubernetes-28.1.0-4.3.aarch64"
								}
							},
							{
								"category": "product_version",
								"name": "python312-kubernetes-28.1.0-4.3.aarch64",
								"product": {
									"name": "python312-kubernetes-28.1.0-4.3.aarch64",
									"product_id": "python312-kubernetes-28.1.0-4.3.aarch64"
								}
							}
						],
						"category": "architecture",
						"name": "aarch64"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python310-kubernetes-28.1.0-4.3.ppc64le",
								"product": {
									"name": "python310-kubernetes-28.1.0-4.3.ppc64le",
									"product_id": "python310-kubernetes-28.1.0-4.3.ppc64le"
								}
							},
							{
								"category": "product_version",
								"name": "python311-kubernetes-28.1.0-4.3.ppc64le",
								"product": {
									"name": "python311-kubernetes-28.1.0-4.3.ppc64le",
									"product_id": "python311-kubernetes-28.1.0-4.3.ppc64le"
								}
							},
							{
								"category": "product_version",
								"name": "python312-kubernetes-28.1.0-4.3.ppc64le",
								"product": {
									"name": "python312-kubernetes-28.1.0-4.3.ppc64le",
									"product_id": "python312-kubernetes-28.1.0-4.3.ppc64le"
								}
							}
						],
						"category": "architecture",
						"name": "ppc64le"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python310-kubernetes-28.1.0-4.3.s390x",
								"product": {
									"name": "python310-kubernetes-28.1.0-4.3.s390x",
									"product_id": "python310-kubernetes-28.1.0-4.3.s390x"
								}
							},
							{
								"category": "product_version",
								"name": "python311-kubernetes-28.1.0-4.3.s390x",
								"product": {
									"name": "python311-kubernetes-28.1.0-4.3.s390x",
									"product_id": "python311-kubernetes-28.1.0-4.3.s390x"
								}
							},
							{
								"category": "product_version",
								"name": "python312-kubernetes-28.1.0-4.3.s390x",
								"product": {
									"name": "python312-kubernetes-28.1.0-4.3.s390x",
									"product_id": "python312-kubernetes-28.1.0-4.3.s390x"
								}
							}
						],
						"category": "architecture",
						"name": "s390x"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python310-kubernetes-28.1.0-4.3.x86_64",
								"product": {
									"name": "python310-kubernetes-28.1.0-4.3.x86_64",
									"product_id": "python310-kubernetes-28.1.0-4.3.x86_64"
								}
							},
							{
								"category": "product_version",
								"name": "python311-kubernetes-28.1.0-4.3.x86_64",
								"product": {
									"name": "python311-kubernetes-28.1.0-4.3.x86_64",
									"product_id": "python311-kubernetes-28.1.0-4.3.x86_64"
								}
							},
							{
								"category": "product_version",
								"name": "python312-kubernetes-28.1.0-4.3.x86_64",
								"product": {
									"name": "python312-kubernetes-28.1.0-4.3.x86_64",
									"product_id": "python312-kubernetes-28.1.0-4.3.x86_64"
								}
							}
						],
						"category": "architecture",
						"name": "x86_64"
					},
					{
						"branches": [
							{
								"category": "product_name",
								"name": "openSUSE Tumbleweed",
								"product": {
									"name": "openSUSE Tumbleweed",
									"product_id": "openSUSE Tumbleweed",
									"product_identification_helper": {
										"cpe": "cpe:/o:opensuse:tumbleweed"
									}
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python310-kubernetes-28.1.0-4.3.aarch64 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python310-kubernetes-28.1.0-4.3.aarch64"
				},
				"product_reference": "python310-kubernetes-28.1.0-4.3.aarch64",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python310-kubernetes-28.1.0-4.3.ppc64le as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python310-kubernetes-28.1.0-4.3.ppc64le"
				},
				"product_reference": "python310-kubernetes-28.1.0-4.3.ppc64le",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python310-kubernetes-28.1.0-4.3.s390x as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python310-kubernetes-28.1.0-4.3.s390x"
				},
				"product_reference": "python310-kubernetes-28.1.0-4.3.s390x",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python310-kubernetes-28.1.0-4.3.x86_64 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python310-kubernetes-28.1.0-4.3.x86_64"
				},
				"product_reference": "python310-kubernetes-28.1.0-4.3.x86_64",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python311-kubernetes-28.1.0-4.3.aarch64 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python311-kubernetes-28.1.0-4.3.aarch64"
				},
				"product_reference": "python311-kubernetes-28.1.0-4.3.aarch64",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python311-kubernetes-28.1.0-4.3.ppc64le as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python311-kubernetes-28.1.0-4.3.ppc64le"
				},
				"product_reference": "python311-kubernetes-28.1.0-4.3.ppc64le",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python311-kubernetes-28.1.0-4.3.s390x as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python311-kubernetes-28.1.0-4.3.s390x"
				},
				"product_reference": "python311-kubernetes-28.1.0-4.3.s390x",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python311-kubernetes-28.1.0-4.3.x86_64 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python311-kubernetes-28.1.0-4.3.x86_64"
				},
				"product_reference": "python311-kubernetes-28.1.0-4.3.x86_64",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python312-kubernetes-28.1.0-4.3.aarch64 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python312-kubernetes-28.1.0-4.3.aarch64"
				},
				"product_reference": "python312-kubernetes-28.1.0-4.3.aarch64",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python312-kubernetes-28.1.0-4.3.ppc64le as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python312-kubernetes-28.1.0-4.3.ppc64le"
				},
				"product_reference": "python312-kubernetes-28.1.0-4.3.ppc64le",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python312-kubernetes-28.1.0-4.3.s390x as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python312-kubernetes-28.1.0-4.3.s390x"
				},
				"product_reference": "python312-kubernetes-28.1.0-4.3.s390x",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python312-kubernetes-28.1.0-4.3.x86_64 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python312-kubernetes-28.1.0-4.3.x86_64"
				},
				"product_reference": "python312-kubernetes-28.1.0-4.3.x86_64",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2018-20060",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2018-20060"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "urllib3 before version 1.23 does not remove the Authorization HTTP header when following a cross-origin redirect (i.e., a redirect that differs in host, port, or scheme). This can allow for credentials in the Authorization header to be exposed to unintended hosts or transmitted in cleartext.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"openSUSE Tumbleweed:python310-kubernetes-28.1.0-4.3.aarch64",
					"openSUSE Tumbleweed:python310-kubernetes-28.1.0-4.3.ppc64le",
					"openSUSE Tumbleweed:python310-kubernetes-28.1.0-4.3.s390x",
					"openSUSE Tumbleweed:python310-kubernetes-28.1.0-4.3.x86_64",
					"openSUSE Tumbleweed:python311-kubernetes-28.1.0-4.3.aarch64",
					"openSUSE Tumbleweed:python311-kubernetes-28.1.0-4.3.ppc64le",
					"openSUSE Tumbleweed:python311-kubernetes-28.1.0-4.3.s390x",
					"openSUSE Tumbleweed:python311-kubernetes-28.1.0-4.3.x86_64",
					"openSUSE Tumbleweed:python312-kubernetes-28.1.0-4.3.aarch64",
					"openSUSE Tumbleweed:python312-kubernetes-28.1.0-4.3.ppc64le",
					"openSUSE Tumbleweed:python312-kubernetes-28.1.0-4.3.s390x",
					"openSUSE Tumbleweed:python312-kubernetes-28.1.0-4.3.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2018-20060",
					"url": "https://www.suse.com/security/cve/CVE-2018-20060"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1119376 for CVE-2018-20060",
					"url": "https://bugzilla.suse.com/1119376"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1216275 for CVE-2018-20060",
					"url": "https://bugzilla.suse.com/1216275"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Tumbleweed:python310-kubernetes-28.1.0-4.3.aarch64",
						"openSUSE Tumbleweed:python310-kubernetes-28.1.0-4.3.ppc64le",
						"openSUSE Tumbleweed:python310-kubernetes-28.1.0-4.3.s390x",
						"openSUSE Tumbleweed:python310-kubernetes-28.1.0-4.3.x86_64",
						"openSUSE Tumbleweed:python311-kubernetes-28.1.0-4.3.aarch64",
						"openSUSE Tumbleweed:python311-kubernetes-28.1.0-4.3.ppc64le",
						"openSUSE Tumbleweed:python311-kubernetes-28.1.0-4.3.s390x",
						"openSUSE Tumbleweed:python311-kubernetes-28.1.0-4.3.x86_64",
						"openSUSE Tumbleweed:python312-kubernetes-28.1.0-4.3.aarch64",
						"openSUSE Tumbleweed:python312-kubernetes-28.1.0-4.3.ppc64le",
						"openSUSE Tumbleweed:python312-kubernetes-28.1.0-4.3.s390x",
						"openSUSE Tumbleweed:python312-kubernetes-28.1.0-4.3.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 2.6,
						"baseSeverity": "LOW",
						"vectorString": "CVSS:3.0/AV:A/AC:H/PR:N/UI:R/S:U/C:L/I:N/A:N",
						"version": "3.0"
					},
					"products": [
						"openSUSE Tumbleweed:python310-kubernetes-28.1.0-4.3.aarch64",
						"openSUSE Tumbleweed:python310-kubernetes-28.1.0-4.3.ppc64le",
						"openSUSE Tumbleweed:python310-kubernetes-28.1.0-4.3.s390x",
						"openSUSE Tumbleweed:python310-kubernetes-28.1.0-4.3.x86_64",
						"openSUSE Tumbleweed:python311-kubernetes-28.1.0-4.3.aarch64",
						"openSUSE Tumbleweed:python311-kubernetes-28.1.0-4.3.ppc64le",
						"openSUSE Tumbleweed:python311-kubernetes-28.1.0-4.3.s390x",
						"openSUSE Tumbleweed:python311-kubernetes-28.1.0-4.3.x86_64",
						"openSUSE Tumbleweed:python312-kubernetes-28.1.0-4.3.aarch64",
						"openSUSE Tumbleweed:python312-kubernetes-28.1.0-4.3.ppc64le",
						"openSUSE Tumbleweed:python312-kubernetes-28.1.0-4.3.s390x",
						"openSUSE Tumbleweed:python312-kubernetes-28.1.0-4.3.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-07-12T00:00:00Z",
					"details": "low"
				}
			],
			"title": "CVE-2018-20060"
		},
		{
			"cve": "CVE-2019-11324",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2019-11324"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "The urllib3 library before 1.24.2 for Python mishandles certain cases where the desired set of CA certificates is different from the OS store of CA certificates, which results in SSL connections succeeding in situations where a verification failure is the correct outcome. This is related to use of the ssl_context, ca_certs, or ca_certs_dir argument.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"openSUSE Tumbleweed:python310-kubernetes-28.1.0-4.3.aarch64",
					"openSUSE Tumbleweed:python310-kubernetes-28.1.0-4.3.ppc64le",
					"openSUSE Tumbleweed:python310-kubernetes-28.1.0-4.3.s390x",
					"openSUSE Tumbleweed:python310-kubernetes-28.1.0-4.3.x86_64",
					"openSUSE Tumbleweed:python311-kubernetes-28.1.0-4.3.aarch64",
					"openSUSE Tumbleweed:python311-kubernetes-28.1.0-4.3.ppc64le",
					"openSUSE Tumbleweed:python311-kubernetes-28.1.0-4.3.s390x",
					"openSUSE Tumbleweed:python311-kubernetes-28.1.0-4.3.x86_64",
					"openSUSE Tumbleweed:python312-kubernetes-28.1.0-4.3.aarch64",
					"openSUSE Tumbleweed:python312-kubernetes-28.1.0-4.3.ppc64le",
					"openSUSE Tumbleweed:python312-kubernetes-28.1.0-4.3.s390x",
					"openSUSE Tumbleweed:python312-kubernetes-28.1.0-4.3.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2019-11324",
					"url": "https://www.suse.com/security/cve/CVE-2019-11324"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1132900 for CVE-2019-11324",
					"url": "https://bugzilla.suse.com/1132900"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Tumbleweed:python310-kubernetes-28.1.0-4.3.aarch64",
						"openSUSE Tumbleweed:python310-kubernetes-28.1.0-4.3.ppc64le",
						"openSUSE Tumbleweed:python310-kubernetes-28.1.0-4.3.s390x",
						"openSUSE Tumbleweed:python310-kubernetes-28.1.0-4.3.x86_64",
						"openSUSE Tumbleweed:python311-kubernetes-28.1.0-4.3.aarch64",
						"openSUSE Tumbleweed:python311-kubernetes-28.1.0-4.3.ppc64le",
						"openSUSE Tumbleweed:python311-kubernetes-28.1.0-4.3.s390x",
						"openSUSE Tumbleweed:python311-kubernetes-28.1.0-4.3.x86_64",
						"openSUSE Tumbleweed:python312-kubernetes-28.1.0-4.3.aarch64",
						"openSUSE Tumbleweed:python312-kubernetes-28.1.0-4.3.ppc64le",
						"openSUSE Tumbleweed:python312-kubernetes-28.1.0-4.3.s390x",
						"openSUSE Tumbleweed:python312-kubernetes-28.1.0-4.3.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 4,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.0/AV:L/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
						"version": "3.0"
					},
					"products": [
						"openSUSE Tumbleweed:python310-kubernetes-28.1.0-4.3.aarch64",
						"openSUSE Tumbleweed:python310-kubernetes-28.1.0-4.3.ppc64le",
						"openSUSE Tumbleweed:python310-kubernetes-28.1.0-4.3.s390x",
						"openSUSE Tumbleweed:python310-kubernetes-28.1.0-4.3.x86_64",
						"openSUSE Tumbleweed:python311-kubernetes-28.1.0-4.3.aarch64",
						"openSUSE Tumbleweed:python311-kubernetes-28.1.0-4.3.ppc64le",
						"openSUSE Tumbleweed:python311-kubernetes-28.1.0-4.3.s390x",
						"openSUSE Tumbleweed:python311-kubernetes-28.1.0-4.3.x86_64",
						"openSUSE Tumbleweed:python312-kubernetes-28.1.0-4.3.aarch64",
						"openSUSE Tumbleweed:python312-kubernetes-28.1.0-4.3.ppc64le",
						"openSUSE Tumbleweed:python312-kubernetes-28.1.0-4.3.s390x",
						"openSUSE Tumbleweed:python312-kubernetes-28.1.0-4.3.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-07-12T00:00:00Z",
					"details": "low"
				}
			],
			"title": "CVE-2019-11324"
		}
	]
}
